### ISSUE TITLE
Proper error screen when "Cannot confirm an offline reservation after event start"

### ISSUE THREAD

**Issue by Praitheesh** [exteso/alf.io#197]
When users try to book the ticket for event which already started below screen is coming up.

![image](https://cloud.githubusercontent.com/assets/2231868/18235287/59aae7a2-735c-11e6-8f47-39da6787c3ef.png)

error stack saying 

```
11:24:57.435 [qtp211649273-21] ERROR alfio.controller.ControllerExceptionHandler - unexpected exception
java.lang.IllegalArgumentException: Cannot confirm an offline reservation after event start
    at org.apache.commons.lang3.Validate.isTrue(Validate.java:155) ~[commons-lang3-3.4.jar:3.4]
    at alfio.manager.TicketReservationManager.getOfflinePaymentWaitingPeriod(TicketReservationManager.java:479) ~[main/:?]
    at alfio.controller.ReservationController.lambda$null$1(ReservationController.java:163) ~[main/:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_91]
    at alfio.controller.ReservationController.lambda$showPaymentPage$3(ReservationController.java:132) ~[main/:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_91]
    at alfio.controller.ReservationController.showPaymentPage(ReservationController.java:131) ~[main/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
```

Message should clear to users.

**Comment by syjer** [comment]
Thanks for the bug report :) I'll have a look!

**Comment by praburajaraman** [comment]
+1

**Comment by Praitheesh** [comment]
@syjer  I'm happy to work this issue. Please give more details behind "Cannot confirm an offline reservation after event start" ? does this mean after event start no one can't buy ticket ?

**Comment by Praitheesh** [comment]
I have added below logic
- if event began already and has only offline payment method then display warning message at event show-event page and disable forward button to reservation/payment page. 
- if even began already and has multiple payment method including offline payment then not show offline payment as option in reservation page
