### ISSUE TITLE
Cannot create new event, error on form??

### ISSUE THREAD

**Issue by Reedyuk** [exteso/alf.io#205]
Hi,
I'm trying to create an event, but i cannot submit one as there is an error on the form, but i dont know what the error is?
Firstly, what is the error? and secondly, could we have an error message displayed? 

<img width="1465" alt="screen shot 2016-09-14 at 21 01 22" src="https://cloud.githubusercontent.com/assets/3853006/18527810/39e67e68-7abe-11e6-9bb8-d2cb85dc3296.png">

**Comment by cbellone** [comment]
Hi Andrew,

It looks like you're using an outdated version of alf.io.
This problem should be fixed in 1.8. Could you please install the new
version and try to reproduce the error?

Il 14-set-2016 10:00 PM, "Andrew Reed" <notifications@github.com> ha
scritto:

**Comment by Reedyuk** [comment]
ok, i will try in a moment. Thanks

**Comment by Reedyuk** [comment]
I tried to deploy 1.8.war to my heroku setup but its failing.
```
2016-09-14T20:36:34.529875+00:00 app[web.1]: Sep 14, 2016 8:36:34 PM org.apache.coyote.AbstractProtocol pause
2016-09-14T20:36:34.544025+00:00 app[web.1]: INFO: Pausing ProtocolHandler ["http-nio-14796"]
2016-09-14T20:36:35.220989+00:00 app[web.1]: 2016-09-14 20:36:35,220 FATAL Unable to register shutdown hook because JVM is shutting down.
2016-09-14T20:36:35.327128+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2016-09-14T20:36:35.335852+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2016-09-14T20:36:36.205473+00:00 app[web.1]: Expanding alfio-1.8.war into /app/target/tomcat.8967/webapps/expanded
2016-09-14T20:36:36.205491+00:00 app[web.1]: Adding Context  for /app/target/tomcat.8967/webapps/expanded
2016-09-14T20:36:36.528819+00:00 app[web.1]: Sep 14, 2016 8:36:36 PM org.apache.coyote.AbstractProtocol init
2016-09-14T20:36:36.528833+00:00 app[web.1]: INFO: Initializing ProtocolHandler ["http-nio-8967"]
2016-09-14T20:36:36.551194+00:00 app[web.1]: Sep 14, 2016 8:36:36 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
2016-09-14T20:36:36.551198+00:00 app[web.1]: INFO: Using a shared selector for servlet write/read
2016-09-14T20:36:36.554706+00:00 app[web.1]: Sep 14, 2016 8:36:36 PM org.apache.catalina.core.StandardService startInternal
2016-09-14T20:36:36.554708+00:00 app[web.1]: INFO: Starting service Tomcat
2016-09-14T20:36:36.555541+00:00 app[web.1]: Sep 14, 2016 8:36:36 PM org.apache.catalina.core.StandardEngine startInternal
2016-09-14T20:36:36.555542+00:00 app[web.1]: INFO: Starting Servlet Engine: Apache Tomcat/8.0.30
2016-09-14T20:36:37.005810+00:00 app[web.1]: Sep 14, 2016 8:36:37 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
2016-09-14T20:36:37.005821+00:00 app[web.1]: INFO: No global web.xml found
2016-09-14T20:36:42.137034+00:00 app[web.1]: Sep 14, 2016 8:36:42 PM org.apache.jasper.servlet.TldScanner scanJars
2016-09-14T20:36:42.137050+00:00 app[web.1]: INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2016-09-14T20:36:43.169044+00:00 app[web.1]: Sep 14, 2016 8:36:43 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:36:43.169056+00:00 app[web.1]: INFO: Spring WebApplicationInitializers detected on classpath: [alfio.config.Initializer@2cc6509b, alfio.config.SecurityInitializer@e5e9c8]
2016-09-14T20:36:43.353199+00:00 app[web.1]: Sep 14, 2016 8:36:43 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:36:43.353202+00:00 app[web.1]: INFO: Initializing Spring root WebApplicationContext
2016-09-14T20:36:44.677003+00:00 app[web.1]: 20:36:44.676 [localhost-startStop-1] INFO  alfio.config.DataSourceConfiguration - Detected cloud provider: HEROKU, database: PGSQL
2016-09-14T20:36:47.279912+00:00 app[web.1]: 20:36:47.279 [localhost-startStop-1] INFO  alfio.config.DataSourceConfiguration - Quartz scheduler configured to run!
2016-09-14T20:36:48.977187+00:00 app[web.1]: Sep 14, 2016 8:36:48 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:36:48.977200+00:00 app[web.1]: INFO: Initializing Spring FrameworkServlet 'dispatcher'
2016-09-14T20:36:51.380051+00:00 app[web.1]: 20:36:51.379 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - performing migration from previous version, if any
2016-09-14T20:36:51.425190+00:00 app[web.1]: 20:36:51.425 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - done.
2016-09-14T20:36:51.425447+00:00 app[web.1]: 20:36:51.425 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - initialized alf.io version 1.8 
2016-09-14T20:36:51.481680+00:00 app[web.1]: Sep 14, 2016 8:36:51 PM org.apache.coyote.AbstractProtocol start
2016-09-14T20:36:51.481683+00:00 app[web.1]: INFO: Starting ProtocolHandler ["http-nio-8967"]
```

**Comment by cbellone** [comment]
Could you please paste the complete log? Do you see any Exception in
there?To me it looks like the application has been successfully initialized:

initialized alf.io version 1.8

Il 14-set-2016 10:38 PM, "Andrew Reed" <notifications@github.com> ha
scritto:

**Comment by Reedyuk** [comment]
here is the server stacktrace.
```
2016-09-14T20:41:22.768131+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-09-14T20:41:24.132379+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2016-09-14T20:41:24.136780+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2016-09-14T20:41:24.116803+00:00 app[web.1]: 2016-09-14 20:41:24,114 localhost-startStop-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Cannot add new shutdown hook as this is not started. Current state: STOPPED
2016-09-14T20:41:24.116823+00:00 app[web.1]: 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.addShutdownCallback(DefaultShutdownCallbackRegistry.java:113)
2016-09-14T20:41:24.116825+00:00 app[web.1]: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
2016-09-14T20:41:24.116828+00:00 app[web.1]: 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
2016-09-14T20:41:24.116829+00:00 app[web.1]: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
2016-09-14T20:41:24.116830+00:00 app[web.1]: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
2016-09-14T20:41:24.116831+00:00 app[web.1]: 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
2016-09-14T20:41:24.116831+00:00 app[web.1]: 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
2016-09-14T20:41:24.116832+00:00 app[web.1]: 	at org.apache.logging.log4j.jcl.LogAdapter.getContext(LogAdapter.java:39)
2016-09-14T20:41:24.116833+00:00 app[web.1]: 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
2016-09-14T20:41:24.116834+00:00 app[web.1]: 	at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:40)
2016-09-14T20:41:24.116838+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5478)
2016-09-14T20:41:24.116838+00:00 app[web.1]: 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
2016-09-14T20:41:24.116839+00:00 app[web.1]: 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
2016-09-14T20:41:24.116841+00:00 app[web.1]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-09-14T20:41:24.116842+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-09-14T20:41:24.851571+00:00 heroku[web.1]: Process exited with status 143
2016-09-14T20:41:25.218382+00:00 app[web.1]: Expanding alfio-1.7.4.war into /app/target/tomcat.57661/webapps/expanded
2016-09-14T20:41:25.218432+00:00 app[web.1]: Adding Context  for /app/target/tomcat.57661/webapps/expanded
2016-09-14T20:41:25.804391+00:00 app[web.1]: Sep 14, 2016 8:41:25 PM org.apache.coyote.AbstractProtocol init
2016-09-14T20:41:25.804402+00:00 app[web.1]: INFO: Initializing ProtocolHandler ["http-nio-57661"]
2016-09-14T20:41:25.833711+00:00 app[web.1]: Sep 14, 2016 8:41:25 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
2016-09-14T20:41:25.833714+00:00 app[web.1]: INFO: Using a shared selector for servlet write/read
2016-09-14T20:41:25.836388+00:00 app[web.1]: Sep 14, 2016 8:41:25 PM org.apache.catalina.core.StandardService startInternal
2016-09-14T20:41:25.836390+00:00 app[web.1]: INFO: Starting service Tomcat
2016-09-14T20:41:25.837357+00:00 app[web.1]: Sep 14, 2016 8:41:25 PM org.apache.catalina.core.StandardEngine startInternal
2016-09-14T20:41:25.837358+00:00 app[web.1]: INFO: Starting Servlet Engine: Apache Tomcat/8.0.30
2016-09-14T20:41:26.193731+00:00 heroku[web.1]: State changed from starting to up
2016-09-14T20:41:26.357042+00:00 app[web.1]: Sep 14, 2016 8:41:26 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
2016-09-14T20:41:28.918697+00:00 app[web.1]: Sep 14, 2016 8:41:28 PM org.apache.jasper.servlet.TldScanner scanJars
2016-09-14T20:41:28.918715+00:00 app[web.1]: INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2016-09-14T20:41:29.215833+00:00 app[web.1]: Sep 14, 2016 8:41:29 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:41:29.215846+00:00 app[web.1]: INFO: Spring WebApplicationInitializers detected on classpath: [alfio.config.SecurityInitializer@6d00e8c4, alfio.config.Initializer@259cbf6b]
2016-09-14T20:41:29.347340+00:00 app[web.1]: Sep 14, 2016 8:41:29 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:41:29.347343+00:00 app[web.1]: INFO: Initializing Spring root WebApplicationContext
2016-09-14T20:41:30.112600+00:00 app[web.1]: 20:41:30.110 [localhost-startStop-1] INFO  alfio.config.DataSourceConfiguration - Detected HEROKU cloud provider
2016-09-14T20:41:32.088259+00:00 app[web.1]: 20:41:32.087 [localhost-startStop-1] INFO  alfio.config.DataSourceConfiguration - Quartz scheduler configured to run!
2016-09-14T20:41:33.389110+00:00 app[web.1]: Sep 14, 2016 8:41:33 PM org.apache.catalina.core.ApplicationContext log
2016-09-14T20:41:35.578327+00:00 app[web.1]: 20:41:35.578 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - performing migration from previous version, if any
2016-09-14T20:41:35.625891+00:00 app[web.1]: 20:41:35.625 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - done.
2016-09-14T20:41:35.625966+00:00 app[web.1]: 20:41:35.625 [localhost-startStop-1] INFO  alfio.config.ConfigurationStatusChecker - initialized alf.io version 1.7.4 
2016-09-14T20:41:35.650772+00:00 app[web.1]: Sep 14, 2016 8:41:35 PM org.apache.coyote.AbstractProtocol start
2016-09-14T20:41:35.650774+00:00 app[web.1]: INFO: Starting ProtocolHandler ["http-nio-57661"]
```

**Comment by Reedyuk** [comment]
hang on, wrong log

**Comment by Reedyuk** [comment]
actually this is really weird, im getting a 302 error and its redirecting lots of times.
This was from 1 request to the root directory:
```
2016-09-14T20:47:23.686487+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=f0e36b23-7ebc-49e1-befc-4839a1d82025 fwd="81.141.107.136" dyno=web.1 connect=0ms service=4ms status=302 bytes=169
2016-09-14T20:47:23.914079+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=8bc542af-6111-45f0-8b79-a7db0790a09e fwd="81.141.107.136" dyno=web.1 connect=0ms service=7ms status=302 bytes=169
2016-09-14T20:47:24.027905+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=6153e8a9-c8c1-4cfa-ab8c-e614a417e02d fwd="81.141.107.136" dyno=web.1 connect=0ms service=3ms status=302 bytes=169
2016-09-14T20:47:24.128777+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=755ea6cf-feb9-4b8c-947f-abe1f5ae60c5 fwd="81.141.107.136" dyno=web.1 connect=0ms service=3ms status=302 bytes=169
2016-09-14T20:47:24.232734+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=cf4d15db-2532-4da7-aeff-46311342452d fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:24.334089+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=0236c405-87f5-4dbc-b010-3fe156d1d7be fwd="81.141.107.136" dyno=web.1 connect=0ms service=4ms status=302 bytes=169
2016-09-14T20:47:24.465090+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=254c1ed3-421c-416b-a36e-cddeed9ece6a fwd="81.141.107.136" dyno=web.1 connect=1ms service=15ms status=302 bytes=169
2016-09-14T20:47:24.680347+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=81db9f21-dc24-4132-9796-72e83f974de3 fwd="81.141.107.136" dyno=web.1 connect=1ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.030814+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=7756e363-52bb-406c-82b1-ce9d26614e95 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:41.892167+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=4022ce0a-cc84-454d-8f82-5294c87f795f fwd="81.141.107.136" dyno=web.1 connect=3ms service=5ms status=302 bytes=169
2016-09-14T20:47:42.134846+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=2130656d-8a8f-4457-bd01-8a5fbf5b24ec fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.267393+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=0a3ce3c3-6274-404c-a5b2-3b9da641f9f6 fwd="81.141.107.136" dyno=web.1 connect=1ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.369584+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=eeac76b8-f6a9-421a-bc4d-ae62eacb23cb fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.495555+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=e2b29dab-f1af-49d6-8647-8a01b2d4bfca fwd="81.141.107.136" dyno=web.1 connect=1ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.596074+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=3d17415e-21cb-4b25-b162-3038b9bcab42 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.695804+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=56853cf5-f1f6-42f8-a22a-00aea7d8085f fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.827711+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=1232e117-dcf9-4193-8ec7-4b70d9ac37be fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:42.948524+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=7289634d-47ca-409e-b249-99631fc94402 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.071470+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=6e802fab-8c80-4214-949e-083a0acdf5fc fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.176641+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=435568fa-eae8-4b04-8e47-5fbb4f1d433d fwd="81.141.107.136" dyno=web.1 connect=0ms service=6ms status=302 bytes=169
2016-09-14T20:47:43.466183+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=855c85a7-e0d4-46db-8bc7-ea59a59a924d fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.590300+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=ace448ba-d60c-47df-9368-98c2bd9763ad fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.691024+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=94621112-497b-42e0-9c99-9ae45838dc6d fwd="81.141.107.136" dyno=web.1 connect=1ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.800013+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=b45d1d2d-d406-45c1-a0cb-00ec153a384c fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:43.928393+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=1126785e-7658-4507-9040-396d32bf1775 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:44.032510+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=e97ad2b3-da9d-41db-a355-e3cc27025e97 fwd="81.141.107.136" dyno=web.1 connect=2ms service=2ms status=302 bytes=169
2016-09-14T20:47:44.180330+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=a2a7404b-ec34-4082-ba5a-7141970229d5 fwd="81.141.107.136" dyno=web.1 connect=1ms service=2ms status=302 bytes=169
2016-09-14T20:47:44.297789+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=df18057f-6260-463e-a4a9-999ee5b2ec2c fwd="81.141.107.136" dyno=web.1 connect=0ms service=12ms status=302 bytes=169
2016-09-14T20:47:44.398088+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=b353b3e6-9d38-4baa-a87a-27d3541607e4 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:44.514981+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=0820c0a1-6670-4a5d-a199-021cdd1306b8 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:44.654359+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=4a995933-f5d9-4584-ab6f-7b73ed9a24a5 fwd="81.141.107.136" dyno=web.1 connect=0ms service=6ms status=302 bytes=169
2016-09-14T20:47:44.759650+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=5d0e1abc-df20-4cae-8924-0b815a1b3d10 fwd="81.141.107.136" dyno=web.1 connect=0ms service=5ms status=302 bytes=169
2016-09-14T20:47:44.903993+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=213e7042-84f2-43c1-8c42-54b0aa30b352 fwd="81.141.107.136" dyno=web.1 connect=6ms service=9ms status=302 bytes=169
2016-09-14T20:47:45.026108+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=a4e1081d-e6c0-4a7b-ae2c-ee55f6d067d7 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:45.129598+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=a5e7ac04-cf47-4fc6-9ed7-85f3849529d1 fwd="81.141.107.136" dyno=web.1 connect=3ms service=2ms status=302 bytes=169
2016-09-14T20:47:45.230910+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=850e6f03-0794-4116-8920-873befd27e26 fwd="81.141.107.136" dyno=web.1 connect=0ms service=1ms status=302 bytes=169
2016-09-14T20:47:45.330421+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=65a1de06-7424-4636-a669-d42548b2d71f fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:45.443509+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=7f8d8196-e132-4542-aba1-a581a17dda67 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:45.543498+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=be3afd22-f64a-4971-bb53-288181fed3a9 fwd="81.141.107.136" dyno=web.1 connect=0ms service=1ms status=302 bytes=169
2016-09-14T20:47:45.648544+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=7a33ea9a-951c-4966-82a1-3b3077ac6c0b fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
2016-09-14T20:47:45.747291+00:00 heroku[router]: at=info method=GET path="/" host=somesiteonheroku.herokuapp.com request_id=e9348f0e-55e2-4feb-a63e-eb518fecd0b4 fwd="81.141.107.136" dyno=web.1 connect=0ms service=2ms status=302 bytes=169
```

**Comment by Reedyuk** [comment]
There is no error, it just seems to be redirecting like crazy. I tried several browsers, so its not cached data. Still the same issue. Redirect madness!

**Comment by cbellone** [comment]
That's weird. My guess is that it has something to do with HTTPS redirect
and X-Forwarded-Proto header somehow missing.

Could you please open another issue for this? Please put also all the
config data we'd need to reproduce the problem in there.

Once we solve the redirect problem we'l get back to this issue.

Thanks for your help!

Il 14-set-2016 10:53 PM, "Andrew Reed" <notifications@github.com> ha
scritto:

There is no error, it just seems to be redirecting like crazy. I tried
several browsers, so its not cached data. Still the same issue. Redirect
madness!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/exteso/alf.io/issues/205#issuecomment-247149684>, or mute
the thread

**Comment by Reedyuk** [comment]
ok no problem, thanks

**Comment by cbellone** [comment]
Hi @Reedyuk ,
what's the status for this? Are you able to reproduce it also with the 1.8?

**Comment by Reedyuk** [comment]
Its working, thanks
